name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Increased timeout

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: List files to deploy
      run: |
        echo "Files to be deployed:"
        ls -la
        echo "Current directory: $PWD"
        echo "Directory contents:"
        find . -type f -not -path '*/\.*'

    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        rm -rf node_modules || true
        rm -rf __pycache__ || true
        rm -rf .pytest_cache || true
        zip -r deploy.zip . -x "*.git*" "*.pyc" "__pycache__/*"
        echo "Package contents:"
        unzip -l deploy.zip

    - name: Deploy to Azure Web App
      id: deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inventory-app-sean'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip

    - name: Check deployment status
      if: always()
      run: |
        echo "Deployment step status: ${{ steps.deploy.outcome }}"
        echo "Checking app status..."
        curl -I https://inventory-app-sean.azurewebsites.net || true
        echo "Deployment completed"
        echo "App URL: https://inventory-app-sean.azurewebsites.net"
