name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create deployment package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        Compress-Archive -Path * -DestinationPath deploy.zip -Force
      shell: pwsh

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inventory-app-sean'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
        startup-command: 'startup.cmd'
