name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Prepare deployment package
      run: |
        # Create deployment package structure
        mkdir -p deploy
        cp -r * deploy/ 2>/dev/null || :
        rm -rf deploy/.git* deploy/deploy
        
        # Create deployment package
        cd deploy
        zip -r ../deploy.zip .
        cd ..
        
        echo "Created deployment package:"
        ls -lh deploy.zip

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inventory-app-sean'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip

    - name: Post-deployment check
      run: |
        echo "Deployment completed"
        echo "App URL: https://inventory-app-sean.azurewebsites.net"
